### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by grayvity** [pekim/tedious-connection-pool#60]
I saw https://github.com/tediousjs/tedious/issues/917 this issue. But why didn't you fix in the master branch?

Version:
"tedious": "^6.4.0",
"tedious-connection-pool": "^1.0.5",

Code:

function callProcedure(pool, name, params, ip='') {
    return new Promise((resolve, reject) => {
        pool.acquire(function (err, connection) {
            var data = [];

            var request = new tedious.Request(name,  function (err, count, rows) {
                if (err) {
                    //don't need to close the connection, put it back to pool
                    connection.release();
                    logger.error(`${ip}:${name}: ${err.stack}`)
                    reject(`Error occured when executing request: ${err.stack}`)
                    
                }
                else {
                    //handle completion for current connection and request object
                    //don't need to close the connection, put it back to pool
                    connection.release();
                }
            });

            if (params != null && params.length > 0) {
                //add parameter to request, parameter should be initiated at each class
                for (var i = 0, len = params.length; i < len; i++) {
                    request.addParameter(params[i].name, params[i].type, params[i].value)
                }
            }

            request.on('row', function (columns) {
                var obj = {};
                for (var i = 0, len = columns.length; i < len; i++) {
                    obj[columns[i].metadata.colName] = columns[i].value;
                }
                data.push(obj);
            });
            
            request.on('doneProc', function (rowCount, more, returnStatus) {
                logger.info(`${ip}:${name}:Stored procedure ${name} executed, rows ${rowCount}, more ${more}, status ${returnStatus}`);
                resolve(JSON.stringify({data}))
            });

            if (connection != null) {
                connection.callProcedure(request);
            }
            else {
                logger.error(`${ip}:${name}: Custom error => Connection is null!`)
                reject('Custom error => Connection is null!')
            }
        });
    });
}

Ianchocks said:
Hi @notestyle, are you having the same 'callback' issue as #917? If so are you also using tedious-connection-pool?

Edit: We actually don't have merge permissions for the tedious-connection-pool since it is a different repository than tedious itself.

**Comment by Oscar-Silva** [comment]
Same issue here.

when i tried `connection.execSql()`

i get a error message: 

> G:\Developer\CLive\clive-server-v2\node_modules\tedious\lib\data-types\nvarchar.js:75
>     cb();
>     ^
> 
> TypeError: cb is not a function
>     at Object.writeParameterData (G:\Developer\CLive\clive-server-v2\node_modules\tedious\lib\data-types\nvarchar.js:75:5)
>     at new RpcRequestPayload (G:\Developer\CLive\clive-server-v2\node_modules\tedious-connection-pool\node_modules\tedious\lib\rpcrequest-payload.js:95:12)
>     at Connection.execSql (G:\Developer\CLive\clive-server-v2\node_modules\tedious-connection-pool\node_modules\tedious\lib\connection.js:883:58)
>     at Object.callback (G:\Developer\CLive\clive-server-v2\src\db\controllers\usuario.js:103:24)
>     at ConnectionPool.setUsed (G:\Developer\CLive\clive-server-v2\node_modules\tedious-connection-pool\lib\connection-pool.js:216:12)
>     at Connection.<anonymous> (G:\Developer\CLive\clive-server-v2\node_modules\tedious-connection-pool\lib\connection-pool.js:110:21)
>     at emitNone (events.js:106:13)
>     at Connection.emit (events.js:208:7)
>     at Connection.processedInitialSql (G:\Developer\CLive\clive-server-v2\node_modules\tedious-connection-pool\node_modules\tedious\lib\connection.js:822:19)
>     at Connection.message (G:\Developer\CLive\clive-server-v2\node_modules\tedious-connection-pool\node_modules\tedious\lib\connection.js:1381:21)

**Comment by HuguesGauthier** [comment]
Hello ? can you fix this ?

**Comment by romullosantos** [comment]
Is there other option to tedious-connection-pool?
